version: "3"

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=secure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=bans.cowboy@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  python:
    build: ./python-scripts
    labels:
      - "traefik.enable=false"

    command: bash -c "python discord_db.py && sleep 5 && python run_all.py"
    environment:
      - DATABASE_PATH=/app/db/league.db
    env_file:
      - .env.python
    volumes:
      - ./db:/app/db
    restart: "no"

  nextjs:
    build: ./nextjs-app
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`radekomsa.site`)"
      - "traefik.http.routers.nextjs.entrypoints=web,websecure"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    environment:
      - DATABASE_PATH=/app/db/league.db
      - NEXTAUTH_URL=https://radekomsa.site
      - AUTH_SECRET=5nfxJAUzLoY+m53Qdm/mRXFurIZi0MSDA7+uNBcR9LQ=
      - AUTH_DISCORD_ID=1342432214910238730
      - AUTH_DISCORD_SECRET=6lEc2TH-RYu28Fgt10BqXIXrjlvlpby8
      - ADMIN_IDS="261319928320098304,662288348114845719,246806085111906304"

    volumes:
      - ./db:/app/db
    depends_on:
      - python
      - traefik
    restart: always
